### ISSUE TITLE
Caffe Installation

### ISSUE THREAD

**Issue by lucarei** [AndrejOrsula/drl_grasping#102]
Hello. I had different problems to install Caffe. In order to simplify things, I worked to install just caffe without your updates to that library: compiling just caffe works. After, I substitute your files in each correct folder, recompile caffe and I had these errors that I cannot understand.
![5BD04026-E62D-4797-A97A-3C4C68AC2BBF](https://user-images.githubusercontent.com/128145979/226634592-bd5d213c-4466-47ca-84c4-c10cedfa05ee.png)
![49E409D3-40D0-45CD-92B7-1CACE1A8C944](https://user-images.githubusercontent.com/128145979/226634602-5bbf8a7f-e574-4731-9511-babdca54a34b.png)

**Comment by AndrejOrsula** [comment]
Hello,

This appears to be an unrelated issue.
The `drl_grasping` repository does not utilize Caffe. The `pytorch` implementation of O-CNN is used (not Caffe). Therefore, you don't need to compile/install Caffe if you want to test this repository.

Try following the instructions of [README.md](https://github.com/AndrejOrsula/drl_grasping/blob/master/README.md#instructions) (and consider testing this project via Docker first before trying a local installation).

Closing due to irrelevancy because Caffe is not used within this project.
